Лабораторна iterator
IvanKoptev/cxx-tasks pull request #2
Opened 2019-04-09 16:27 UTC by IvanKoptev

```
Test project /home/Ivan/cxx-tasks/build
    Start 1: tests_iterator:iterator::operations
1/4 Test #1: tests_iterator:iterator::operations .........   Passed    0.00 sec
    Start 2: tests_iterator:iterator::write
2/4 Test #2: tests_iterator:iterator::write ..............   Passed    0.00 sec
    Start 3: tests_iterator:iterator::copy_from_vector
3/4 Test #3: tests_iterator:iterator::copy_from_vector ...   Passed    0.00 sec
    Start 4: tests_iterator:iterator::copy_to_vector
4/4 Test #4: tests_iterator:iterator::copy_to_vector .....   Passed    0.00 sec

100% tests passed, 0 tests failed out of 4

Label Time Summary:
tests_iterator    =   0.01 sec*proc (4 tests)

Total Test time (real) =   0.01 sec

```

2019-04-10 12:29 UTC, igsha requested changes
Необходимы доработки

2019-04-10 12:29 UTC, igsha commented on iterator/include/iterator.hpp
> +    using diff_type = typename image_iterator::difference_type;
всё, помимо конструктора, должно быть с прятано в private секции

2019-04-10 12:29 UTC, igsha commented on iterator/include/iterator.hpp
> +    size_t index_ = 0;
здесь должен быть итератор на начало строки `Iterator row_`

2019-04-10 12:29 UTC, igsha commented on iterator/include/iterator.hpp
> +        auto n = x.base() - this->base();
вычислить расстояние можно как сумму разниц строк и столбцов. Только делить надо надо на stride, а не width

2019-04-10 12:29 UTC, igsha commented on iterator/include/iterator.hpp
> +        auto n = x.base() - this->base();
и здесь все вычисления умещаются в одну строчку

2019-04-10 12:29 UTC, igsha commented on iterator/include/iterator.hpp
> +        if (width_- index_ % (int)stride_ == 0)
сложное условие. А если `width_ - index_` будет меньше нуля? Не очень понятно зачем тут вообще нужен `width_`.
Гораздо удобнее проверить, что `base_reference()` стал меньше начала строки и вычесть из начала строки страйд, а потом `base_reference()` присвоить конец полученной строки.

2019-04-10 12:29 UTC, igsha commented on iterator/include/iterator.hpp
> +            index_ += stride_ - width_ + 1;
вот тут видно, что `base_reference()` и `index_` - это одно и тоже

2019-04-10 12:29 UTC, igsha commented on iterator/include/iterator.hpp
> +        int res = n/abs(n) * (stride_count * (stride_ - width_) + abs(n));
непонятно, зачему тут `abs` использовать, так как в `rest` уже была проверка на знак. Логика здесь должна пересекаться с `distance_to`:
1. получаем расстояние (дельту) от начала строки до полученного элемента
2. смещаем начало строки на количество строк в дельте
3. корректируем `base_reference()` на оставшиеся элементы из дельты
4. ещё одна корректировка на отрицательную дельту (только здесь есть проверка на отрицательность и нет ни одного `abs`)

2019-04-11 14:20 UTC, IvanKoptev commented
@igsha, все исправил, помимо переноса всего в private секцию

2019-04-11 14:22 UTC, IvanKoptev commented on iterator/include/iterator.hpp
> +    using diff_type = typename image_iterator::difference_type;
при переносе методов distance_to, advance и т.д. возникает ошибка:
 ```
error: ‘void image_iterator<Iterator>::increment() [with Iterator = __gnu_cxx::__normal_iterator<int*, std::vector<int> >]’ is private within this context
           f.increment();
```

2019-04-11 15:35 UTC, igsha commented on iterator/include/iterator.hpp
> +    using diff_type = typename image_iterator::difference_type;
надо зафрендить `iterator_core_access`

2019-04-11 20:45 UTC, IvanKoptev commented
@igsha, готово

2019-04-12 05:19 UTC, igsha approved these changes
Да, так гораздо лучше. За эту лабу, пожалуй, 8 баллов поставлю.

2019-04-12 05:19 UTC, merged